name: Verify Package Installers

on:
  push:
    paths:
      - 'tests/test-autoconfig.xml'
  pull_request:
    paths:
      - 'tests/test-autoconfig.xml'
  workflow_dispatch:

jobs:
  verify:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
    
    - name: Run verification script
      run: python verify.py
    
    - name: Upload installers as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package-installers
        path: '*_installer.exe'
